version: "3.8"
services:
  db:
    image: postgres:16
    container_name: fintrack_db
    environment:
      POSTGRES_DB: FinTrackAI
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintrack"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@local
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db
volumes:
  db_data: